### ISSUE TITLE
[Feature suggestion] Support configuring starting heading level class

### ISSUE THREAD

**Issue by edwardhorsford** [DFE-Digital/govuk_markdown#14]
The [node version of this library](https://github.com/x-govuk/govuk-markdown) supports config to set what starting heading class should be used for h1s and below. We should port the same config on this library.

This would let a consumer of this library set that h1s should use `govuk-heading-l` or any other design system heading level they choose.

[Relevant lines from the npm module](https://github.com/x-govuk/govuk-markdown/blob/main/index.js#L17-L34)

[Relevant lines in this module](https://github.com/DFE-Digital/govuk_markdown/blob/main/lib/govuk_markdown/renderer.rb#L32-L44)

Note: arguably the default heading level class should be `govuk-heading-l`, not `govuk-heading-xl` but that could come in a later major version bump.

**Comment by HettieS** [comment]
implemented this as part of 2.0.0b1
